=== ransom-ransom/wt/exp-5-xml-schema/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2002/XMLSchema">
<xs:element name="bank">
<xs:complexType>
<xs:sequence>
<xs:element name="BankAccount" minOccurs="1" maxOccurs="5"/>
</xs:sequence>
</xs:complexType>
<xs:element>
<xs:element name="BankAccount">
<xs:complexType>
<xs:sequence>
<xs:element name="Branch" type="xs:string"/>
<xs:element name="AccountNumber" type="xs:integer"/>
<xs:element name="AccountHolder" type="xs:string"/>
<xs:element name="Balance" type="xs:decimal"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== ransom-ransom/wt/exp-5-xml-schema/xml-file.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="html/text/css"?>

<!-- XML program using XML schema -->

<bank xmlns:xsi="http://wwww.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
<BankAccount>
<Branch>Tokyo</Branch>
<AccountNumber>987456123</AccountNumber>
<AccountHolder>First-name Last-name</AccountHolder>
<Balance>10000</Balance>
</BankAccount>
<BankAccount>
<Branch>London</Branch>
<AccountNumber>123456789</AccountNumber>
<AccountHolder>First-name Last-Name</AccountHolder>
<Balance>10000</Balance>
</BankAccount>
<BankAccount>
<Branch>New York</Branch>
<AccountNumber>12478564812</AccountNumber>
<AccountHolder>First-name Last-name</AccountHolder>
<Balance>1000</Balance>
</BankAccount>
</bank>
